version: '3.4'

services:

  culinaryrecipes_postgresql:
    image: postgres:14.1
    
  # netschool_rabbitmq:
  #   image: rabbitmq:management
            
  culinaryrecipes_api:
    image: ${DOCKER_REGISTRY-}culinaryrecipesapi
    build:
      context: .
      dockerfile: Systems/Api/CulinaryRecipes.Api/Dockerfile
    depends_on:
      - culinaryrecipes_postgresql
      # - netschool_rabbitmq

  # dsrnetschool_worker_1:
  #   image: ${DOCKER_REGISTRY-}netschoolworker
  #   build:
  #     context: .
  #     dockerfile: Systems/Worker/NetSchool.Worker/Dockerfile
  #   depends_on:
  #     - netschool_postgresql
  #     - netschool_rabbitmq
  #     - netschool_api

  # dsrnetschool_worker_2:
  #   image: ${DOCKER_REGISTRY-}netschoolworker
  #   build:
  #     context: .
  #     dockerfile: Systems/Worker/NetSchool.Worker/Dockerfile
  #   depends_on:
  #     - netschool_postgresql
  #     - netschool_rabbitmq
  #     - netschool_api 