version: '3.4'

services:
  culinaryrecipes_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "45432:5432"
    networks:
      - shared_culinaryrecipes_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data
    

  culinaryrecipes_api:
    ports:
      - "10000:8080"
    networks:
      - shared_culinaryrecipes_net
    env_file:
      - env.api

  culinaryrecipes_identity:
    ports:
      - "10001:8080"
    networks:
      - shared_culinaryrecipes_net
    env_file:
      - env.identity

networks:
  shared_culinaryrecipes_net:
    name: culinary_recipes
    driver: bridge