version: '3.4'

services:

  culinaryrecipes_postgresql:
    image: postgres:14.1
            
  culinaryrecipes_api:
    image: ${DOCKER_REGISTRY-}culinaryrecipesapi
    build:
      context: .
      dockerfile: Systems/Api/CulinaryRecipes.Api/Dockerfile
    depends_on:
      - culinaryrecipes_postgresql

  culinaryrecipes_identity:
    image: ${DOCKER_REGISTRY-}culinaryrecipesidentity
    build:
      context: .
      dockerfile: Systems/Identity/CulinaryRecipes.Identity/Dockerfile
    depends_on:
      - culinaryrecipes_postgresql
      - culinaryrecipes_api