version: '3.4'

services:

  culinaryrecipes_postgresql:
    image: postgres:14.1
            
  culinaryrecipes_api:
    image: ${DOCKER_REGISTRY-}culinaryrecipesapi
    build:
      context: .
      dockerfile: Systems/Api/CulinaryRecipes.Api/Dockerfile
    depends_on:
      - culinaryrecipes_postgresql

  culinaryrecipes_identity:
    image: ${DOCKER_REGISTRY-}culinaryrecipesidentity
    build:
      context: .
      dockerfile: Systems/Identity/CulinaryRecipes.Identity/Dockerfile
    depends_on:
      - culinaryrecipes_postgresql
      - culinaryrecipes_api

  culinaryrecipes_rabbitmq:
    image: rabbitmq:management

  culinaryrecipes_emailsenderworker:
    image: ${DOCKER_REGISTRY-}culinaryrecipesemailsenderworker
    build:
      context: .
      dockerfile: Systems/Workers/CulinaryRecipes.Workers.EmailSenderWorker/Dockerfile
    depends_on:
      - culinaryrecipes_rabbitmq
      - culinaryrecipes_api

  culinaryrecipes_usersubscriptionemailsenderworker1:
    image: ${DOCKER_REGISTRY-}culinaryrecipesusersubscriptionemailsenderworker
    build:
      context: .
      dockerfile: Systems/Workers/CulinaryRecipes.Workers.UserSubscriptionEmailSenderWorker/Dockerfile
    depends_on:
      - culinaryrecipes_rabbitmq
      - culinaryrecipes_api

  culinaryrecipes_usersubscriptionemailsenderworker2:
    image: ${DOCKER_REGISTRY-}culinaryrecipesusersubscriptionemailsenderworker
    build:
      context: .
      dockerfile: Systems/Workers/CulinaryRecipes.Workers.UserSubscriptionEmailSenderWorker/Dockerfile
    depends_on:
      - culinaryrecipes_rabbitmq
      - culinaryrecipes_api

  culinaryrecipes_recipesubscriptionemailsenderworker1:
    image: ${DOCKER_REGISTRY-}culinaryrecipesrecipesubscriptionemailsenderworker
    build:
      context: .
      dockerfile: Systems/Workers/CulinaryRecipes.Workers.RecipeSubscriptionEmailSenderWorker/Dockerfile
    depends_on:
      - culinaryrecipes_rabbitmq
      - culinaryrecipes_api

  culinaryrecipes_recipesubscriptionemailsenderworker2:
    image: ${DOCKER_REGISTRY-}culinaryrecipesrecipesubscriptionemailsenderworker
    build:
      context: .
      dockerfile: Systems/Workers/CulinaryRecipes.Workers.RecipeSubscriptionEmailSenderWorker/Dockerfile
    depends_on:
      - culinaryrecipes_rabbitmq
      - culinaryrecipes_api

  culinaryrecipes_redis:
    image: redis